### ISSUE TITLE
Using Websockets only to connect peers

### ISSUE THREAD

**Issue by brickgale** [peers/peerjs-server#100]
Is it possibe to use websockets only to create a connection? I want something like a fallback if ever webrtc isn't supported on the client/browser, since websockets are already on the peerjs servers. Also tho I think the peerjs client is tightly coupled with the webrtc function. It would be great just to have this especially safari or ios browsers doesn't support webrtc yet.

**Comment by afrokick** [comment]
Sorry, but it is WebRTC mechanism, not WebSocket.

You cannot use websocket transport instead of webrtc's transports

**Comment by brickgale** [comment]
I actually made a `fallback` for it a while back. It overrides the functions tho.

**Comment by brickgale** [comment]
stripped out the webrtc code, something like this: https://gist.github.com/brickgale/87924d9b50823b2181a4c6edd0bfce0b
