### ISSUE TITLE
Demo is not work 

### ISSUE THREAD

**Issue by tabvn** [peers/peerjs-server#103]
http://cdn.peerjs.com/demo/videochat 
it say pc it undefined.

**Comment by tabvn** [comment]
error screenshot: http://cloud.tabvn.com/nsaesk.png

**Comment by viktorstrate** [comment]
You have to pass in another person's _user id_, to the right of the call button. You can see your id above the call button.

**Comment by luispimenta** [comment]
try this : https://valarpirai.github.io/video-chat-app/
