### ISSUE TITLE
Erro 404 not found

### ISSUE THREAD

**Issue by luispimenta** [peers/peerjs-server#107]
I tried the deploy button on heroku and also checked the project on my computer, both I get

catcher.js: 197 GET https://intake-live.herokuapp.com/peerjs/pimenta/onlineusers 404 (Not Found)

and

GET https://3283317e.ngrok.io/peerjs/pimenta/onlineusers 404 (Not Found)

What am I doing wrong ?

**Comment by kidandcat** [comment]
Demo is down, a new one will be deployed soon this month
