### ISSUE TITLE
peerjs site and demo server is DOWN

### ISSUE THREAD

**Issue by matteoannibali** [peers/peerjs-server#108]
I tried to deploy it to heroku but i got some errors...

Error: getaddrinfo ENOTFOUND https https:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by kas2000** [comment]
Is it going to be fixed or not? Should we all change our code?

**Comment by kidandcat** [comment]
The website is online again, in a few days the demo will be online too

**Comment by matteoannibali** [comment]
http://cdn.peerjs.com/0.3.9/peer.js not found

**Comment by kidandcat** [comment]
Use this: https://cdnjs.cloudflare.com/ajax/libs/peerjs/0.3.9/peer.js

**Comment by matteoannibali** [comment]
👍

Il giorno mar 5 giu 2018 alle ore 11:50 Jairo Caro-Accino Viciana <
notifications@github.com> ha scritto:
