### ISSUE TITLE
Provide cloud peerjs server over https/wss

### ISSUE THREAD

**Issue by Masterxilo** [peers/peerjs-server#111]
Because of https://github.com/peers/peerjs-server/issues/90 the cloud peerjs server is now useless for video calls.

We currently only get

http://0.peerjs.com:9000/

but we would need

https://0.peerjs.com:9000/

Yes we should run our own server to control the load, but for evaluation purposes it would be cool if you could provide this.

**Comment by kidandcat** [comment]
Sorry for the lack of documentation about this, but you have https://0.peerjs.com/

**Comment by Masterxilo** [comment]
Perfect. If you could, that would be awesome - the fewer configuration to get something cool going the more motivation people will have to go with this!
