### ISSUE TITLE
Unable to connect to Peer server via https

### ISSUE THREAD

**Issue by pavelv99** [peers/peerjs-server#116]
`  <script>

  var usernameInput = document.getElementById('username_input')
  var btnConnect = document.getElementById('connect_peer')
  var recepientInput = document.getElementById('recepient_input')
  var btnCall = document.getElementById('call_btn')

  var peer

  btnConnect.onclick = function() {
    peer = new Peer(usernameInput.value, { host: 'localhost', port: 9000, debug:3 })
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
    navigator.getUserMedia({video: true, audio: true}, function(stream) {
      btnCall.onclick = function() {
        var call = peer.call(recepientInput.value, stream);
        call.on('stream', function(remoteStream) {
          // Show stream in some <video> element.
          alert('Calling')
        });
      }
    }, function(err) {
      console.log('Failed to get local stream' ,err);
    });

    callsListener(peer)
  }

  function callsListener(peer) {
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
    peer.on('call', function(call) {
      navigator.getUserMedia({video: true, audio: true}, function(stream) {
        call.answer(stream); // Answer the call with an A/V stream.
        call.on('stream', function(remoteStream) {
          alert('Call')
          // Show stream in some video/canvas element.
        });
      }, function(err) {
        alert('One good guy is calling u...')
        console.log('Failed to get local stream' ,err);
      });
    });
  }

  </script>`

Peer server launched via base `peerjs --port 9000 --key peerjs`
Try this https://maflic.ru

**Comment by kidandcat** [comment]
Sorry but I can't see any PeerJS code in that website:
view-source:https://maflic.ru/

**Comment by afrokick** [comment]
I close the issue. But if it exists - feel free to leave a comment, i'll reopen it.
