### ISSUE TITLE
Setup video conference with more than 3 people using peerjs

### ISSUE THREAD

**Issue by AngeSohone** [peers/peerjs-server#117]
Actually have setup an application and able to connect users to get stream of sender. it's work fine with 3 users, the problem is when another one join conference, can't receive stream.
want to know if is due to bandwidth ? limit of mesh architecture?  or something else?

Thanks

**Comment by afrokick** [comment]
Could you please attach logs from browser/server? Seems like user's issue.

**Comment by AngeSohone** [comment]
Have error on console just that if i have more than 3 users, start from the fourth , all of them couldn't receive remote stream

**Comment by afrokick** [comment]
Seems like non peers-server issue but peerjs. Please, open a new issue in peerjs repository if it exists
