### ISSUE TITLE
Combining with existing express server

### ISSUE THREAD

**Issue by Niksac** [peers/peerjs-server#119]
Hi,

a week ago I started integrating the peerjs-server into my existing express application.
By now, the instructions have been removed from the README file.

Before I continue my efforts:
Are you stopping support for this approach?

Nik

**Comment by kidandcat** [comment]
Yes and No. Correct me if I'm wrong @afrokick , but PeerServer will no longer be a node library. Instead it will be splitted in a core library (which you can use to create your custom server) and a default implementation (this will be PeerServer, but it will be an application, not a library).

So you should wait a little and be pending of PeerServer progress.

Maybe @afrokick can give you an aproximate date so you can start at least using master branch.

**Comment by afrokick** [comment]
The idea is separate all code into smaller parts (services) and create two repos. The first - a core. The second is 'ready-to-use' application.

Just now i created ready-to-use app. I need more time to create core(as it was before).

**Comment by Niksac** [comment]
Thanks guys!
I will stick to the public server until the core is ready.

Thanks for the great library
