### ISSUE TITLE
How to connect to peerjs server from desktop application C#

### ISSUE THREAD

**Issue by Varooneh** [peers/peerjs-server#123]
Hi all.

I've a desktop application written in C# also I've a websocket and tcp/udp library for C#. Now, can I connect from application to peerjs with websocket or tcp or udp client? how to?

Thank you for help me.

**Comment by afrokick** [comment]
Do you want to use WebRTC with C#?

**Comment by Varooneh** [comment]
Yes, I need this.

**Comment by afrokick** [comment]
There is a README where you can find a description for our API.

I have no idea about how to use WebRTC in C#. This issue not related to peerjs-server, because it is just signaling.

**Comment by maxpavlov** [comment]
You would need:

1. to use something like this: https://github.com/radioman/WebRtc.NET
2. write the peer that is currently written in TypeScript for PeerJS with C# over the WebRTC.

As WebRTC is mostly a challenge to more restricted browsers, then to a less restricted desktop and mobile apps, webrtc isn't commonly available on desktop. Even with nodejs you would need to use electron wrapper (which is basically a running instance of Chrome in the background) to get the WebRTC connectivity. 

So it is doable, but even if you get it to work, you won't be able to support it alone. I say until Google or Microsoft needs WebRTC on the desktop, we are out of LTS luck :)
