### ISSUE TITLE
No error when client tries to establish a data connection with a non-existing ID

### ISSUE THREAD

**Issue by bilo1967** [peers/peerjs-server#127]
See details about my setup below.
This is the issue;

- The client connects with the server and gets its ID
- The client tries to connect with a non-existent ID
- The client receives no error from the server
- The server outputs to the console: `Error: TypeError: Cannot destructure property 'realm' of 'undefined' or 'null'`

The same code **works fine** if I connect to the public server.

Any clue?

My setup:

I've set up a plain-vanilla PeerJS server on my CentOS6 distro. I've made no changes to the server code and I start it with: 
```bash
/opt/peerjs-server/bin/peerjs  \
    --port 9000 \
    --sslkey /etc/letsencrypt/live/my.own.domain/privkey.pem  \
    --sslcert /etc/letsencrypt/live/my.own.domain  \
    --path '/'
```

In /opt/peerjs-server/config/index.js I have:
```javascript
module.exports = {
  port: 9000,
  expire_timeout: 5000,
  path: '/',
  concurrent_limit: 5000,
  allow_discovery: false,
  proxied: false,
  cleanup_out_msgs: 1000,
  ssl: {
    key: '/etc/letsencrypt/live/my.own.domain/privkey.pem',
    cert: '/etc/letsencrypt/live/my.own.domain/cert.pem'
  }
};
```

P.S.
Where do I find the server log file and how do I set the server log level?

**Comment by kidandcat** [comment]
Hi, it looks latest PeerServer version is not stable yet. @afrokick was developing it. Meanwhile you should be ok with the version of the public server which I've published in the branch: v0.2.9 test it and write if it works in your case.

PD: I wouldn't recommend to let PeerServer (or any NodeJS service) to manage SSL. Public PeerServer SSL is managed by a bastion Caddyserver.

**Comment by bilo1967** [comment]
> Hi, it looks latest PeerServer version is not stable yet. @afrokick was developing it. Meanwhile you should be ok with the version of the public server which I've published in the branch: v0.2.9 test it and write if it works in your case.

Seems like it's working fine, thank you!

> PD: I wouldn't recommend to let PeerServer (or any NodeJS service) to manage SSL. Public PeerServer SSL is managed by a bastion Caddyserver.

Ok. Is there any guide to configure Caddy to proxy the PeerServer?

**Comment by kidandcat** [comment]
As easy as: 

```
0.peerjs.com {
  proxy / http://localhost:9000 {
    websocket
  }
  tls your@email.com
}
```

**Comment by d07RiV** [comment]
I don't think it's related to clients trying to connect to non existing peers.

Looking at the code in question, I'm not sure what it was even supposed to be doing:

    TypeError: Cannot destructure property `realm` of 'undefined' or 'null'.
        at module.exports (/home/___/peerjs-server/src/messageHandler/index.js:24:18)
        at pruneOutstanding (/home/___/peerjs-server/src/services/messagesExpire/index.js:23:11)
        at Timeout.setTimeout [as _onTimeout] (/home/___/peerjs-server/src/services/messagesExpire/index.js:45:7)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)

`messageHandler` line 24:

    module.exports = ({ realm }) => {

`messagesExpire` around line 23:

        if (!seen[message.src]) {
          messageHandler(null, {
            type: MessageType.EXPIRE,
            src: message.dst,
            dst: message.src
          });
          seen[message.src] = true;
        }

It straight up calls a single argument function with two arguments, first of them being null. I see no way for this code to not crash under any condition.

**Comment by afrokick** [comment]
@bilo1967 we fixed some bugs, could you please try to check the latest version from master branch?

**Comment by bilo1967** [comment]
> 
> 
> @bilo1967 we fixed some bugs, could you please try to check the latest version from master branch?

Did just a quick test and it seems to work fine.
I'll keep this version of the server and let you know if there are problems.

**Comment by afrokick** [comment]
Ok, please reopen an issue if it still exists
