### ISSUE TITLE
Invalide IP address: true when you pass --proxied true in package.json scripts

### ISSUE THREAD

**Issue by fatpandaria** [peers/peerjs-server#128]
it looks like that the type of options.proxied passed by the command line is 'string',  so when you call app.set('trust proxy', 'true') instead of app.set('trust proxy', true) will throw an invalid IP address error.Maybe just pass an Boolean instead of options.proxied?

location: /src/index.js

**Comment by kidandcat** [comment]
Fixed with:

```javascript
  if (options.proxied) {
    app.set('trust proxy', options.proxied === 'false' ? false : options.proxied);
  }
```

That should cover all cases (strings and booleans)
