### ISSUE TITLE
-p and --port options are doing different things

### ISSUE THREAD

**Issue by dorthrithil** [peers/peerjs-server#129]
I can start the server using either `-p=9000` or `--port=9000`. As both are listed as aliases in the options I would expect them to behave identically. However I get the following output:

```
MyMachine:bin myuser$ ./peerjs -p=9000
Started PeerServer on undefined, port: undefined, path: / (v. 0.2.9)
```

vs.

```
MyMachine:bin myuser$ ./peerjs --port=9000 
Started PeerServer on ::, port: 9000, path: / (v. 0.2.9)
```

I'm not able to connect using `-p` as the IP and port seem to be undefined.

**Comment by d07RiV** [comment]
Single character arguments are usually passed in as `-p9000`.

**Comment by afrokick** [comment]
or `-p 9000` with whitespace
