### ISSUE TITLE
Connection issues.

### ISSUE THREAD

**Issue by ChrisFlick** [peers/peerjs-server#131]
Hi I am a bit of a noobie and have been trying to teach myself some networking for a game I am making. I'm using my own PeerServer and have been able to get the clients to connect with the server but seem unable to connect with one another. My server was cloned off this repository while my client side code is:

Client A JavaScript
```
var peer = new Peer(
  "a",
  {
    host: 'Server-IP', 
    port: 9000, 
  }
); 
console.log(peer);

var conn = peer.connect('b');
console.log(conn);
// on open will be launch when you successfully connect to PeerServer
conn.on('open', function() {
  // here you have conn.id
  console.log("sending hi");
  conn.send('hi!');
});

peer.on('connection', function(conn) {
  console.log('connecting to peer');
    conn.on('data', function(data) {
      // Will print 'hi!'
      console.log(data);
    });
  });
````

Client A HTML:
```
<!DOCTYPE html>
<header>
</header>
<body>
</body>
<footer>
        <script src="https://unpkg.com/peerjs@1.0.0/dist/peerjs.min.js"></script>
        <script type="text/javascript" src=a.js></script>
</footer>
```

Client B JavaScript:
```
var peer = new Peer(
  "b",
  {
    host: 'Server-IP', 
    port: 9000, 
  }
); 

var conn = peer.connect('a');
// on open will be launch when you successfully connect to PeerServer
conn.on('open', function(){
  // here you have conn.id
  conn.send('hi!');
});

peer.on('connection', function(conn) {
    conn.on('data', function(data){
      // Will print 'hi!'
      console.log(data);
    });
  });
```

Client B HTML:
```
<!DOCTYPE html>
<header>
</header>
<body>
</body>
<footer>
        <script src="https://unpkg.com/peerjs@1.0.0/dist/peerjs.min.js"></script>
        <script type="text/javascript" src=b.js></script>
</footer>
````

When I run the code in Chrome my Server logs:

> Client connected: a
> Client connected: b

While the Clients log nothing but the two objects in Client A

**Comment by Keko94** [comment]
Same, is the server compatible with the latest PeerJS client ?

**Comment by Keko94** [comment]
It's working with auto generated ID !

**Comment by Keko94** [comment]
Okay I succeeded to manage to make it works with IDs manually setted in both side.
You have to connect to the other one after your own 'open' is ready.

`peer.on('open', function(id) {
            console.log('My peer ID is: ' + id);
            var conn = peer.connect('tryme');
            conn.on('open', function() {
                console.log('Connection ready !');
                // Receive messages
                conn.on('data', function(data) {
                    console.log('Received', data);
                });

                conn.on('error', function(err) {
                    console.log(err);
                });

                // Send messages
                conn.send('Hello!');
            });

        });`

**Comment by afrokick** [comment]
Seems like you solved the issue. I close it. If you have a question, just reopen it.
