### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by thuraucsy** [peers/peerjs-server#132]
I'm using [npm peer@0.2.10](https://www.npmjs.com/package/peer/v/0.2.10) with socket.io using the Express server.

my package.json dependencies 
```
"dependencies": {
   "express": "^4.17.1",
   "peer": "^0.2.10",
   "socket.io": "^1.4.6"
 }
```
**The error does not happen in peer@0.2.8 and my simple code is as follow.**

server.js
```
const express = require('express');
const PeerServer = require('peer').PeerServer;
const ExpressPeerServer = require('peer').ExpressPeerServer;
const socket_io = require('socket.io');

const app = express()
const port = 3000

app.use(function(req, res, next) {
	res.header("Access-Control-Allow-Origin", "*");
	res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
	next();
});

app.get('/', (req, res) => {
	res.sendFile('/var/www/html/mypeer.html');
})

const server = app.listen(port, () => console.log(`Example app listening on port ${port}!`))

const peerserver = ExpressPeerServer(server, {debug: true} );
app.use('/myapp', peerserver);

peerserver.on('error', (client) => {
	console.log('error');
});

peerserver.on('connection', (client) => {
	console.log(`The client ${client} is connected`);
});


var rec_sockio = socket_io.listen(server);
rec_sockio.sockets.on('connection', function(socket) {
	console.log('socket is connected', socket.id);
});

```

mypeer.html 
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Peer Test</title>
</head>
<body>

	<script src="https://unpkg.com/peerjs@1.0.2/dist/peerjs.min.js"></script>
	<script type="text/javascript" src="http://192.168.33.10:3000/socket.io/socket.io.js"></script>
	<script>
		const peer = new Peer({host: '192.168.33.10', port: 3000, path: '/myapp'});
		console.log(`peer`, peer);

		peer.on('error', function(err) {
			console.log(`err`, err);
		});

		var sock_client = io.connect('192.168.33.10:3000');
		sock_client.on('connect', function() {
			console.log(`sock_client connect`);
		});
	</script>
</body>
</html>

```

I got this error
```
WebSocket connection to 'ws://192.168.33.10:3000/socket.io/EIO=3&transport=websocket&sid=tQ5aa4lRzqMlGmX7AAAB' failed: Error during WebSocket handshake: Unexpected response code: 400
```

The error seems having problem with the transport websocket but polling seems okay.

**Comment by d07RiV** [comment]
I'm getting the same error, using apache proxy. Running default script:

    ./peerjs --port 3002 --proxied 1 (it won't accept true here. I tried custom server script, too)

**Comment by afrokick** [comment]
@thuraucsy Did you fix your issue?

**Comment by thuraucsy** [comment]
@afrokick No.

**Comment by linewei** [comment]
I got the same error. use peerjs v0.3 work well. 
I guess peerjs v1.0 can not work with peerserver v0.3 for now.

**Comment by factorin-j** [comment]
Im currently experiencing this as well.
yarn package versions:
```json
{
    "peer": "^0.3.2",
    "peerjs": "^1.2.0",
}
```

here is the reverse proxy in my apache:
```apache
    ProxyRequests off
    ProxyPreserveHost on
    ProxyPass "/peerjs" "ws://127.0.0.01:9000/"
    ProxyPassReverse "/peerjs" "ws://127.0.0.1:9000/"

    <Proxy "*">
        Require all granted
    </Proxy>
```
Do I have some misconfigurations here? 
I always get this error with either `http/ws` and `https/wss`
```
app.min.js?v=1584467674:28347 WebSocket connection to 'wss://peer.local/peerjs?key=peerjs&id=userId&token=5nn8f89pmnp' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by afrokick** [comment]
@factorin-j please attach config for server

**Comment by afrokick** [comment]
@thuraucsy please try a new version 0.4.0

**Comment by lokk3d** [comment]
I have the same problem using peer 0.5.0 and peerjs 1.2.0

**Comment by afrokick** [comment]
I found the issue. will fix it in 0.5.1

**Comment by afrokick** [comment]
Fixed, @lokk3d please test it again. `npm i peer@0.5.1`

**Comment by Programador1RMV** [comment]
i have the v0.5.1 and it doesnt work, it show same error

**Comment by afrokick** [comment]
@Programador1RMV which client version do you use?

**Comment by TgPb** [comment]
I have the same issue with peer 0.5.1 and peerjs 1.2.0

**Comment by Doomguy5** [comment]
I have the same issue with peer 0.5.1 and peerjs 1.2.0 as well

**Comment by Payetus** [comment]
Same issue

**Comment by TgPb** [comment]
in my case issue was fixed in peer 0.5.2

**Comment by ttanhvu1712** [comment]
Same issue when use peerjs 1.1.0/1.2.0 and peer 0.5.1/0.5.2. Deploy server: heroku

**Comment by cgfarmer4** [comment]
same 1.2 and 0.5.3

**Comment by mafikes** [comment]
The same issue. Server "peer": "^0.5.3" and client  1.2.0. :/

**Comment by maivanmanh** [comment]
I got the same issue when using the source code provided in documentation, try peerServer set up in this post: https://www.toptal.com/webrtc/taming-webrtc-with-peerjs. I've tried and it works.
