### ISSUE TITLE
Config overrides path in PeerServer constructor

### ISSUE THREAD

**Issue by d07RiV** [peers/peerjs-server#134]
Passing `path` to `PeerServer` constructor without editing `config/index.js` seems to break the server.

    const server = PeerServer({port: 3002, path: '/', proxied: true});

Config:

    path: '/peerjs',

Results in the endpoint to get IDs being /peerjs/peerjs/id. The client still tries to fetch `/peerjs/id` and gets a 404.

**Comment by d07RiV** [comment]
Investigating further, the CORS is there, but paths seems weird. I create server with `path: '/'`, API is mounted on `/peerjs`, which adds endpoints for `/:key` => v1.public, which adds `/id`. So the resulting endpoint to get an ID is `/peerjs/peerjs/id`.

Suspicious line is in `src/index.js` where it grabs `path` from options object, then deletes it and gets it again from config.

**Comment by afrokick** [comment]
#125 should work now
