### ISSUE TITLE
The path parameter doesn't work.

### ISSUE THREAD

**Issue by leonraw** [peers/peerjs-server#135]
The path parameter doesn't work. I probably found a bug in the source code.
In the 92 Line of the [src/index.js](https://github.com/peers/peerjs-server/blob/master/src/index.js) file. `delete options.path` And not added after. So maybe the user configured path doesn't work? I manually added `options.path = path` in 101 line. And the server is working, maybe...
Oh, its working. But still throw an error like this:
`POST https://balabala.com:9000/peerjs/6eow7206tki00000/3jrd2917drk/id?i=0 401 (Unauthorized).`
`response: Unauthorized.`

**Comment by d07RiV** [comment]
I ran into the same problem (though I named my issue incorrectly). You should set the path in `config/index.js` instead. Though I haven't tried running it with anything other than `/` as path (note that the actual endpoints will still append `peerjs` to it).

**Comment by afrokick** [comment]
#125 @leonraw is it work for you?

**Comment by leonraw** [comment]
> #125 @leonraw is it work for you?

@afrokick yes its work.  I can receive the peer id. But I can't receive `app.json` response.

**Comment by afrokick** [comment]
How you run the app?

`./bin/peerjs --port 9000 --path /` ?

**Comment by leonraw** [comment]
@afrokick yes.
code: `node ./bin/peerjs --port 9000 --path /`.
and i cant get response from `https://ip:9000/` or `https://ip:9000/myapp/`. (http is the same)
the version is 0.2.9.

**Comment by afrokick** [comment]
could you please try the version from master branch?

**Comment by afrokick** [comment]
It works for me on master branch. Please, reopen the issue if it still exists for you.

**Comment by afrokick** [comment]
If you have the same issue, please, check that you use the latest client version. Currently it is `npm i peerjs@1.2.0`
