### ISSUE TITLE
[QUESTION] Is peerjs-server compatible with AWS Elastic Beanstalk? 

### ISSUE THREAD

**Issue by aldovincenti** [peers/peerjs-server#146]
I was wondering if peerjs-server would be compatible with AWS Elastic Beanstalk. 

> Elastic Beanstalk applications should also be as stateless as possible, using loosely coupled, fault-tolerant components that can be scaled out as needed.

Source: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.concepts.design.html

Did anyone try it?

**Comment by kidandcat** [comment]
I don't think so, PeerServer needs a mongoDB, and I'm not sure if it still keeps state in memory @afrokick ?

**Comment by aldovincenti** [comment]
@kidandcat MongoDB? I don't see any reference to it in the documentation...

**Comment by afrokick** [comment]
It stores data in-memory. So, we don't use MongoDB

**Comment by RealHandy** [comment]
I'm trying, and so far, it's not working. I'm getting 502 bad gateway errors internally to EB from health checks pointed at the peerjs-server port. Using application load balancer, which only allows HTTP and HTTPS connections, it may be that peerjs-server doesn't properly handle incoming HTTP requests, or that EB (or nginx in EB) doesn't handle an incoming ws:// request through an HTTP port.

**Comment by RealHandy** [comment]
I've got it working. I use port 9000 to receive both peerjs-server and http requests. My ALB listens on 9000 and passes all the requests through to my server instance.

**Comment by Payetus** [comment]
@RealHandy could you share your Dockerrun.aws.json ?

**Comment by RealHandy** [comment]
@Payetus I don't use docker, unfortunately. But I did do a writeup of my settings on StackOverflow that might be helpful, maybe, possibly?
https://stackoverflow.com/questions/58793966/node-js-server-with-websockets-on-elastic-beanstalk-alb-without-socket-io/58793967#58793967
