### ISSUE TITLE
Allow passing in custom client ID generation function.

### ISSUE THREAD

**Issue by ajmar** [peers/peerjs-server#147]
It would be useful to pass in a custom function to PeerServer or ExpressPeerServer that can be used to generate client IDs, instead of having to do it on the client. I guess this approach should be slightly safer since it will be more difficult for malicious clients to send malicious IDs. Additionally the ID generation may be a large in size function (say if it needs to use an English dictionary).

I've created a fork here that implements this functionality, though I haven't updated the tests yet: https://github.com/ajmar/peerjs-server

Proposed implementation example:
```javascript
const peerserver = ExpressPeerServer(server, {port: 80, path: '/path', key: 'key', debug: true},
	() => {
		const chars = 'abcdefghijklmnopqrstuvwxyz';
		let result = '';
		for (let x=0; x<4; x++) {
			result += chars[Math.floor(Math.random() * chars.length)];
		}
		return result;
	}
);
```

**Comment by liebig** [comment]
Any news here? Would be very interesting for me, too.

**Comment by afrokick** [comment]
@ajmar Thanks! Will release in `0.4.0`
