### ISSUE TITLE
Express PeerServer not working in mobile (iOS)

### ISSUE THREAD

**Issue by anatoli308** [peers/peerjs-server#149]
Hello,

I have tried the Combining with existing express app example and it didnt work on my iphone 10.
I always get the error message "Error: Lost connection to server"

my code is this:

const express = require('express');
const app = express();
const ExpressPeerServer = require('peer').ExpressPeerServer;

var server = require("https").createServer({
key: fs.readFileSync('server.key'),
cert: fs.readFileSync('server.cert')
},expressApp);
const peerserver = ExpressPeerServer(server, options);

app.use('/peerjs', peerserver);

server.listen(443);

frontend:
var peer = new Peer("peer", signalingServer);
var errorFn = e => {
alert(e); //PROBLEM ios Error: lost connection to server
};
peer.on("error", errorFn);
const signalingServer = {
host: '192.168.1.10',
port: 443,
key:'peerjs',
path: '/peerjs'
},
debug: 3
};

**Comment by CFT-Chris** [comment]
@anatoli308 in case you are still facing this problem, add path: '/peerjs' to your options object prior to calling ExpressPeerServer and see if that works for you.

**Comment by anatoli308** [comment]
Thanks for the Reply but i already found the Issue. I Posted it on the peerjs repo-issues if Someone facing the Same Problem
