### ISSUE TITLE
npm release package outdated. Semantic release CI automation?

### ISSUE THREAD

**Issue by ivelin** [peers/peerjs-server#150]
First of all, congratulations for an awesome project!

I noticed that the latest [npm peer](https://www.npmjs.com/package/peer) package is almost a year outdated (v0.2.10, from Aug 2019) as compared to github's latest commits (v0.3, Sep 6, 2019). Just wanted to ask what the release policy is? Is there a plan to move to a semantic release automation?

Thank you,

Ivelin

**Comment by afrokick** [comment]
Hi! We want to rewrite project to ts, it will be 0.3 version. And after some tests in real word we'll publish it as 1.0.0

**Comment by ivelin** [comment]
OK. Understood. I like the strategy of migrating to a safer server side codebase.

In the meanwhile, does it make sense to introduce a semantic release action in order to keep the npm up to date with patches? I'd be happy to help set it up as a PR if there is interest. Here is how I do it for one of my projects which is an extension of peerjs-server:
https://github.com/ambianic/ambianic-pnp/blob/master/.github/workflows/nodejs.yml

The reason I am asking this is because I am actually using the project, but due to the gap between source and npm, I pull the latest source code copy from github which is of-course sub-optimal. I'd rather use and contribute to the main project code instead of managing a fork.

Regards,

Ivelin

**Comment by afrokick** [comment]
Now we publish it manually, so I close the issue.
