### ISSUE TITLE
github sponsors page?

### ISSUE THREAD

**Issue by ivelin** [peers/peerjs-server#153]
Not sure if this is the right place to raise this issue. Is there a plan to introduce a [github sponsor](https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account) page for this project? I see that there are sponsorship links for the peerjs repo, but some of them are outdated and broken. I find the new built-in github sponsorship intuitive and easy to use for sponsors and project maintainers.

**Comment by kidandcat** [comment]
We are already using OpenCollective. I'm happy with it, and we have enough funds to play the public PeerServer + Stun/Turn so . . . maybe in the future
