### ISSUE TITLE
Broadcasting to a tree

### ISSUE THREAD

**Issue by fselcukcan** [peers/peerjs-server#159]
As I have read through the peerjs client api reference one can just stream the same stream from its peer to many other peers simultaneously by just calling multiple peers, please correct me if I am wrong.
I want to make a few number of peers to speak to each other, by call method on peer, and broadcast this audio stream to many other listening-only peers. While doing these I do not want to load all the streaming to listener-only peers work to the original caller peer but to limit its work by a number, say 6, and make each of these 6 peers to stream the same stream to other listener-only peers after this number, 6, and so on.
Is that possible?

**Comment by afrokick** [comment]
Sorry, there is no a feature like broadcasting in peerjs.
