### ISSUE TITLE
Server does not recognize its own clients heartbeats

### ISSUE THREAD

**Issue by ARoddis** [peers/peerjs-server#161]
![grafik](https://user-images.githubusercontent.com/2421679/75607984-ea27f600-5afb-11ea-987f-d25467857ffc.png)

Leeds to this error message in the node.js server:

![grafik](https://user-images.githubusercontent.com/2421679/75607997-fca22f80-5afb-11ea-84fa-7ad86094ab71.png)

caused by the fact, that this check does not contain a heartbeat:

![grafik](https://user-images.githubusercontent.com/2421679/75608006-117ec300-5afc-11ea-9eac-5c96b0e5b1b9.png)

**Comment by ARoddis** [comment]
Hacky fix for someone who has the same problem:

![grafik](https://user-images.githubusercontent.com/2421679/75608173-81417d80-5afd-11ea-8b5f-60f3f9ef2e92.png)

**Comment by afrokick** [comment]
which version of server do you use? Try use the latest version from GitHub.

**Comment by afrokick** [comment]
We released the latest version of peerjs server to npm - 0.3.2 It should works!
