### ISSUE TITLE
Error 401 Unauthorized

### ISSUE THREAD

**Issue by riscoss63** [peers/peerjs-server#166]
Hi i have another problem:
When request POST in this URL :
 `https://peerserver.bulledevoyages.com:9000/myapp/peerjs/be1e695d-a8a4-45cf-9275-07e3159cfc80/0xgivwm45ck/id?i=0` 
I have an unauthorized 401 error.

This my config:
-to launche peerserver:

`./peerjs --port 9000 --key peerjs --sslkey /etc/letsencrypt/live/peerserver.xxx.com/privkey.pem --sslcert /etc/letsencrypt/live/peerserver.xxx.com/fullchain.pem --path /myapp`

-to connect:

`var peer = new Peer({ key: 'peerjs', host: 'peerserver.xxx.com', port: 9000, path: '/myapp', secure: true, debug: 3, config: { "iceServers": [ // Information about ICE servers - Use your own! { "urls": "stun:turn.mysite.com", "username": "xxx", "credential": "xxx" }, { "urls": "turn:turn.mysite.com", "username": "xxx", "credential": "xxx" }, ] } })`

Thank you

EDIT: 
Now i have this error :
`Cannot GET /myapp/peerjs/088ccaf2-b1e1-4033-8ed6-cdfbff9eb687/x4vk0jdaxei/id`

**Comment by riscoss63** [comment]
It's because Cross-Origin Request Blocked ?

**Comment by afrokick** [comment]
which client version do you use?

**Comment by afrokick** [comment]
https://prairie-six-ray.glitch.me - my example works for peerjs client 1.2.0 and peers-server 0.5.1

**Comment by riscoss63** [comment]
i use cdn :
`<script src="https://cdn.jsdelivr.net/npm/peerjs@0.3.20/dist/peer.min.js"></script>`

**Comment by afrokick** [comment]
Try to use 1.2.0 `<script src="https://cdn.jsdelivr.net/npm/peerjs@1.2.0/dist/peerjs.min.js"></script>`

**Comment by riscoss63** [comment]
It work thank you :)
