### ISSUE TITLE
TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by EliasSimoes** [peers/peerjs-server#167]
I had run the server like this: **peerjs --port 9000 --key peerjs --path /myapp**
> Started PeerServer on ::, port: 9000, path: /ndoctor (v. 0.4.0)

My client config is

`**const customGenerationFunction = () => (Math.random().toString(36) + '0000000000000000000').substr(2, 16);
const peer = new Peer({
    debug: 3,
    key: 'peerjs',
    host: 'localhost',
    port: 9000,
    path: '/myapp',
    generateClientId: customGenerationFunction 
})**;`
> Client connected: d3fb454e-ec7a-464d-a855-d458959204b3

But every time i try to make a resquest there i get this error on console:

> TypeError: Cannot read property 'config' of undefined
>     at handle (C:\Program Files\nodejs\node_modules\peer\dist\src\api\middleware\auth\index.js:11:26)
>     at Layer.handle [as handle_request] (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\layer.js:95:5)
>     at trim_prefix (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:317:13)
>     at C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:284:7
>     at param (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:354:14)
>     at param (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:365:14)
>     at param (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:365:14)
>     at param (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:365:14)
>     at Function.process_params (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:410:3)
>     at next (C:\Program Files\nodejs\node_modules\peer\node_modules\express\lib\router\index.js:275:10)
> Client disconnected: d3fb454e-ec7a-464d-a855-d458959204b3

May someone help me with this?

**Comment by afrokick** [comment]
Please update peer to 0.5.1 `npm i peer@0.5.1` and use the latest version of PeerJS `npm i peerjs@1.2.0`

**Comment by rhsu14** [comment]
The documentation is wrong, check https://www.npmjs.com/package/peerjs to see how you should create your peer.

Instead of Peer('string', {obj}) it should be Peer({obj})

**Comment by afrokick** [comment]
Leave a new comment if it still exists
