### ISSUE TITLE
Setting allow_discovery true, still returns "cannot GET /peers"

### ISSUE THREAD

**Issue by MariusVB** [peers/peerjs-server#174]
Hi,

I'm currently trying to run the peerjs-server locally and I need the GET /peers functionality for my app.
I start the server with:
` peerjs --allow_discovery true --port 9000`

However when sending a GET to localhost:9000/peers, I receive "cannot GET /peers". I get the same error using random paths, like localhost:9000/foobar. It seems like the endpoint isn't created at all.
I'm running latest 0.5.2 version.

**Comment by MariusVB** [comment]
The server expects the key in front of the /peers request. By default it can get accessed by /peerjs/peers

**Comment by skitsanos** [comment]
Marius, thanks for the tip. That 'key' is coming from where exactly? any way to set it somehow?

**Comment by MariusVB** [comment]
Using the peerjs CLI, its just a parameter like so:
![image](https://user-images.githubusercontent.com/24921111/94035380-4a95c200-fdc3-11ea-8afb-d6ad996f3399.png)
