### ISSUE TITLE
 Error in connection establishment

### ISSUE THREAD

**Issue by sonoiodc** [peers/peerjs-server#180]
I'm running my own peerjs server on AWS and i managed to create a ssl certificate with certbot;
I did check the certificate from ssllabs.com/ssltest  and Everything looks fine
When I try to connection from the client I receive :
"Error in connection establishment: net::ERR_CERT_REVOKED".

![Schermata 2020-04-16 alle 15 57 40](https://user-images.githubusercontent.com/62805931/79464959-08d64380-7ffb-11ea-8f0d-0c5cc2f2de1f.png)

**Comment by najibghadri** [comment]
Did you solve it?

**Comment by afrokick** [comment]
This issue not related to PeerJS. try to google WebSocket + ERR_CERT_REVOKED

**Comment by sonoiodc** [comment]
I refollowed step by step and it work; 
First I generate the certificate with certbot, than restart the server passing the SSL certificate and finally (since I used a DNS for the certificate) access to the server using the domain name instead of the IP. 

P.S. I think that the problem was that somewhere it pointed to the selfsigned certificate that  I made for test
