### ISSUE TITLE
Undefined of Peer id

### ISSUE THREAD

**Issue by VeeRHunter** [peers/peerjs-server#181]
I am getting this error and I am not sure why I am getting this issue.
http://prntscr.com/s0m8nf

**Comment by afrokick** [comment]
You need to update your certificate. Because https doesn't work. So, you cannot get a ID from server.

**Comment by VeeRHunter** [comment]
What should I update?
I already update certificate for peer server.

**Comment by afrokick** [comment]
The error ERR_CERT_DATE_INVALID in your console related to certificate issue. Try to update cert or sync local time on your pc/laptop.

**Comment by VeeRHunter** [comment]
You mean this certificate is peer server or public server which is including peer code this?


        peer.on('open', function () {
            peer_id = peer.id;
            roomName = peer.id;
        });

        peer.on('call', function (call) {
            var acceptsCall = true;

            window.call = call;

            if (acceptsCall) {
                // Answer the call with your own video/audio stream
                call.answer(window.localStream);

                // Receive data
                call.on('stream', function (stream) {
                    window.peer_stream = stream;
                    onReceiveStream(stream, 'video1');
                });
            } else {
                console.log("Call denied !");
            }
        });
