### ISSUE TITLE
Network Errors for some users

### ISSUE THREAD

**Issue by tiofabby** [peers/peerjs-server#183]
Hello,
I have set up a peerjs server and it works fine for most of users and myself too.
Issue is that for specific users, they are getting connection issues like below:

```
WebSocket connection to 'wss://MY_SERVER_URL_HERE/myapp/peerjs?key=peerjs&id=VyjbNtgYK&token=79405l2kgwv' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
t.start @ 163a1fdccb495353893b.js:2
c4207df439bfa8de9239.js:1 ERROR:  Lost or cannot establish a connection to the signalling server.
```
this is being triggered by following code:

```
peer.on('error', function(err) {
        switch(err.type) {
          case 'network':               // ERROR
            Log.error('Lost or cannot establish a connection to the signalling server.')
            break

```

I am wondering how it can work for me and other and not for some other?
I can ping the server url , it works fine, name is resolved.
Would you have any idea why?
Should I look at firewall issues on these end user machines??
Any idea why this is happening...

Thank you
Fabrice

**Comment by afrokick** [comment]
Sorry, i think it is end users issue, not peerjs.
