### ISSUE TITLE
Is there any working example that uses node, express, and peer?

### ISSUE THREAD

**Issue by cuinjune** [peers/peerjs-server#184]
I spent my whole day trying to set up my app using peer but couldn't succeed so far.

Here's what my server js file looks like:

```
const path = require('path');
const express = require('express');
const { ExpressPeerServer } = require('peer');
const app = express();
const PORT = process.env.PORT || 3000;

// set your static server
app.use(express.static(path.resolve(`${__dirname}/public`)));

// views
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'views/index.html'));
});

// start listening
const server = app.listen(PORT);
console.log('Server is running localhost on port: ' + PORT);

// peerjs
const peerServer = ExpressPeerServer(server, {
    debug: true,
});

app.use('/peerjs', peerServer);

// listeners
peerServer.on('connection', (client) => {
    console.log("Server: Peer connected with ID:", client.id);
});

peerServer.on('disconnect', (client) => {
    console.log("Server: Peer disconnected with ID:", client.id);
});
```
When I run the app, it says `Server: Peer connected with ID: ff1b23c0-9b67-49e3-8461-35405397d3b2` but then a minute later it says `Server: Peer disconnected with ID: ff1b23c0-9b67-49e3-8461-35405397d3b2`.

Also, I failed to make the server connect to the client. The `peer.on('connection', function(conn) {}`function never gets called. I may be missing something.

So I'm trying to find an example code that works but so far I haven't found any example(using node, express, peer) that works.

Can anyone please introduce me to any working example of a node app that uses peer?
All I want is just checking the server-client connection as a first step. (without connection being disconnected automatically)

Thank you in advance.

**Comment by jerlam06** [comment]
I invite you to check my code there: https://github.com/peers/peerjs-server/issues/185
The code that I use works perfectly locally.

**Comment by afrokick** [comment]
You can use this project https://glitch.com/~prairie-six-ray as a base.
