### ISSUE TITLE
Peers won't communicate with one another when server is deployed to the cloud

### ISSUE THREAD

**Issue by jerlam06** [peers/peerjs-server#185]
I have set up a very basic app with two clients: a sender and a receiver, running on localhost. And I have set up my custom peerjs server locally as well, so far so good, the receiver receives the data sent by the sender. However, as soon as I deploy my server into the cloud within kubernetes containers, everything seems to work fine, I see the receiver and the sender connected when I go on host/myapp/peerjs/peers with allow_discovery activated. BUT the sender and the receiver won't communicate together, there is no error message (even with debug on), they connect to the SAME server nicely, but they just somehow do not communicate.

```javascript
// SENDER
document.addEventListener("DOMContentLoaded", (event) => {
  const local = false;

  const peer = new Peer("sender", {
    debug: 3,
    host: local ? "localhost" : "peerjs-server.devspace.host",
    port: local ? "9000" : "443",
    path: "/myapp",
    secure: local ? false : true,
    config: {
      iceServers: [
        { url: "stun:stun1.l.google.com:19302" },
        {
          url: "turn:turn.bistri.com:80",
          credential: "homeo",
          username: "homeo",
        },
      ],
    },
  });

  const conn = peer.connect("receiver");

  peer.on("error", (err) => {
    console.log("error:", err);
  });

  conn.on("open", () => {
    conn.send("hi!");
  });
});
```

```javascript
// RECEIVER
document.addEventListener("DOMContentLoaded", (event) => {
  const local = false;

  const peer = new Peer("receiver", {
    debug: 3,
    host: local ? "localhost" : "peerjs-server.devspace.host",
    port: local ? "9000" : "443",
    path: "/myapp",
    secure: local ? false : true,
    config: {
      iceServers: [
        { url: "stun:stun1.l.google.com:19302" },
        {
          url: "turn:turn.bistri.com:80",
          credential: "homeo",
          username: "homeo",
        },
      ],
    },
  });

  peer.on("error", (err) => {
    console.log("error:", err);
  });

  peer.on("connection", (conn) => {
    conn.on("data", (data) => {
      console.log(data);
    });
  });
});
```

```javascript
// SERVER
const server = app.listen(443);

const peerServer = ExpressPeerServer(server, {
  port: 443,
  debug: true,
  path: "/myapp",
  allow_discovery: true,
  proxied: true,
  //   ssl: {
  //     key: fs.readFileSync("./ssl-dev/key.pem", "utf8"),
  //     cert: fs.readFileSync("./ssl-dev/cert.pem", "utf8"),
  //   },
});

app.use("/", peerServer);

server.on("connection", function (id) {
  console.log("id:", id);
});

server.on("disconnect", function (id) {
  console.log(id + "disconnected");
});

app.use(
  cors({
    credentials: true,
    origin: "*",
    methods: "POST,PUT,GET",
  })
);
app.set("trust proxy", true);
app.use(cookieParser());
```

I am deploying my server with [DevSpace Cloud](https://devspace.cloud/), the SSL is handled by them. I also tried to deploy the server via the docker image proposed by peerjs-server: "peerjs/peerjs-server", to make sure that the problem was not coming from configuration issues on my side, but the problem remains the same.
Furthermore I also tried different protocols (because I was not sure if the communication between peers was only meant to work with a server running on secured port), so different ports...not only 443. But the issue is always the same.
I think I am missing something that I am unaware of which has to do with kubernetes. I would be glad if any one who succeeded where I failed could give me some hand =)

Thanks a lot, and let me know if you need more info!

**Comment by arjun1194** [comment]
are you using https? because to get a peer id you need to serve over https.

**Comment by afrokick** [comment]
Sorry, but this place isn't good for k8s or devops related questions.
