### ISSUE TITLE
Cannot use namespace 'EventEmitter' as a type.ts(2709)

### ISSUE THREAD

**Issue by jpetitte** [peers/peerjs-server#194]
- Give an expressive description of what is went wrong: Line 8, index.d.ts => Cannot use namespace 'EventEmitter' as a type.ts(2709)
  - Version of `peer` you're experiencing this issue: 0.5.3
  - Nodejs version? v12.16.2
  - Platform name and its version (Win, Mac, Linux)? Linux
  - Nice to have: a repository with code to reproduce the issue => reproduces with this repo, master, using TypeScript 3.8.3

Sorry I don't have a solution off the top of my head atm.

**Comment by artisandip7** [comment]
Same issue *Cannot use namespace 'EventEmitter' as a type
peer: 0.5.3
node: 12.16.2
platform: win
typescript: 3.8.3

**Comment by afrokick** [comment]
Fixed in #200
