### ISSUE TITLE
URL not found when trying to run server

### ISSUE THREAD

**Issue by maximus1127** [peers/peerjs-server#199]
Hey guys. I've been using your cloud server for a few weeks now and it's great. Thanks so much for making this product. But now I'm trying to migrate over to my own hosted server. I've followed the commands in the "Run Server" section at the very top of the "usage" area on the home page. Just copy/pasted the global install command, then entered the run command. In my terminal, the server shows that it's successfully running on the port and path designated by the run command. But when I go to the url at 127.0.0.1:9000/myapp, I'm getting a 404 URL not found on this server error. I'm using apache 2.4, not sure if it helps to know that or not.

**Comment by terst6** [comment]
so, what happened? I got the same error

**Comment by maximus1127** [comment]
i wound up using the simple-peer package and Pusher to trade handshake creds instead of running through the peer-js server/client. Let me know if you need any help getting that set up.
