### ISSUE TITLE
peerjs@1.3.1 call.on('close', function(){}); not working

### ISSUE THREAD

**Issue by stevebbs** [peers/peerjs-server#216]
After upgrading from peerjs@1.2.0 to peerjs@1.3.1 I notice that the call.on('close', function(){}); is not working. Nothing happens to the sender end if the receiver stops receiving and nothing happens at the receiver end if the sender stops sending. I've had to revert back to using peerjs@1.2.0 for the time being, hoping a correction will be made.

**Comment by AllanPinheiroDeLima** [comment]
As incredible as it sounds, it is still happening...
Going back to 1.2 worked, but I don't know if it will have any incompatibility
