### ISSUE TITLE
Error: Server has reached its concurrent user limit

### ISSUE THREAD

**Issue by mhungerford** [peers/peerjs-server#217]
On Monday, September 14th at 11 AM PST, the PeerJS-Server cloud instance at 0.peerjs.com reported:
"Error: Server has reached its concurrent user limit"

I see that the limit is 5000 users.  

I'm planning on using peerjs-server cloud for an open-source project for a educational event (Mini Maker Faire), to allow users to get up and running more quickly by utilizing your great cloud service.

Could this cap be increased to support the increased interest in PeerJS lately?
https://github.com/peers/peerjs-server/blob/master/src/config/index.ts
  concurrent_limit: 5000,

Thanks.

**Comment by RamyaAshika** [comment]
Hi, What could be the reason for this? I'm also facing this same issue? @mhungerford

**Comment by SayedMainUddin** [comment]
I have the same issue .but i can not solve the issu.please if anybody already solved,help me.

**Comment by SayedMainUddin** [comment]
@mhungerford did you solve your problem?

**Comment by ElmouradiAmine** [comment]
You need to use your own peer js server and deploy it https://elements.heroku.com/buttons/peers/peerjs-server

**Comment by SayedMainUddin** [comment]
> You need to use your own peer js server and deploy it https://elements.heroku.com/buttons/peers/peerjs-server

I already solved ;
thank you @ElmouradiAmine ElmouradiAmine for your reply;

**Comment by ElmouradiAmine** [comment]
How did you solve it?

**Comment by SayedMainUddin** [comment]
> How did you solve it?

I made a separate server for peerjs. and keep my port on 9000.

**Comment by kidandcat** [comment]
The public server has its own configurations, you are free to deploy your own PeerServer and set your configuration as you wish.
