### ISSUE TITLE
feat: add cors to cli

### ISSUE THREAD

**Issue by xenoterracide** [peers/peerjs-server#221]
```
    peer: ^0.5.3
```
```
 node --version                                                            # services/.../s3-upload -> feature/RS2-1229-s3-upload-schema $
v12.18.3
```

I'd like to have a `--cors` flag added to the command line server for security reasons. We have currently written our own custom server, but this is only to add cors options, I'd really like to extend the docker container (or update it's run command in the docker-compose file) instead of implementing our own server build, which is unlikely to get updated.

**Comment by gabrielcmarinho** [comment]
@michelle @afrokick @ericz @kidandcat — any updates about it?

**Comment by afrokick** [comment]
any PR are welcome)

**Comment by afrokick** [comment]
There was an issue https://github.com/peers/peerjs-server/issues/196
