### ISSUE TITLE
Urgent: Readme quick start is totally broken - doesn't work at all

### ISSUE THREAD

**Issue by codepilotsf** [peers/peerjs-server#230]
Very easy to repeat. I've tried on multiple machines/networks and even had a friend confirm. If you simply do the three steps exactly as shown at the top of the Readme, the browser returns ERR_EMPTY_RESPONSE. The server does not appear to be listening / reachable. 

This is also true using the PeerServer in a node app. The ExpressPeerServer however, does seem to work.

**Comment by codepilotsf** [comment]
Just want to add... Everyone I've shown this too has the same problem. All using current stable or relatively current Node/NPM on MacOS or Ubuntu Linux. This is not limited to just my environment -- it appears to be totally broken for everyone (except maybe Windows users)

**Comment by afrokick** [comment]
Found the issue in https://github.com/peers/peerjs-server/pull/225/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R51 Will fix it in 0.6.1

**Comment by afrokick** [comment]
Fixed, thanks!
