### ISSUE TITLE
Api To make Authentication?

### ISSUE THREAD

**Issue by litch0** [peers/peerjs-server#232]
### I'm having an issue:
I am using your library with Blazor webassembly and my problem is being authentication, I just found out about this repo and saw that it is possible to integrate it into an express app, so does it have any kind of events? like, wen a user connect, and then If i could access the url through this event. 
With this I can use JWT to share information from my .net backend, that was obtained from  my Blazor frontend and at the same time, doesn't allow any non-user to connect to my instance. I have the auth plan setup and I just need to intercept any user connecting to the instance and then to the url, headers or cookies, It could also be an constom event that I wrote.

**Comment by litch0** [comment]
for example:
Lets say I am making an Google Meet Clone, my backend share the JWT that contains:
```JS
{
    userId:"",
    Room:""
}
```
And then use the userId to look at the database and see if the user has acess to the room it is trying to enter, then return an acess token (this would mean that the JWT is one time use), after this, when the user connects to the room, It present the acess token. Or just use JWT as the acess token as the acess token and make all the verifcation when it tries to connect to the room.

**Comment by litch0** [comment]
I work mostly with C# in the backend thats why i problably didn't notice it earlier, but it turns out that
```JS
const { ExpressPeerServer } = require('peer');
const express = require('express')
const app = express()
const port = 3000

const peerServer = ExpressPeerServer(app, {
    path: '/myapp'
});

app.use('/peerjs', (req, res, next) => {
    // here we can manipulate the request before it is sent to Peerjs server
    // If we don't authorize the user is just return a forbiden status code
    return peerServer(req, res, next);
});
```

my corrent problem is how to pass the token to the backend i tried `  path: '/myapp?access_token=SOMETHING'` but peerjs doens't seem to allow it, I will also try cookies and then let you guys known, but I havent found an args or something similar in the constructor of Peer({})

**Comment by mahmoudafer** [comment]
> I work mostly with C# in the backend thats why i problably didn't notice it earlier, but it turns out that
> 
> ```js
> const { ExpressPeerServer } = require('peer');
> const express = require('express')
> const app = express()
> const port = 3000
> 
> const peerServer = ExpressPeerServer(app, {
>     path: '/myapp'
> });
> 
> app.use('/peerjs', (req, res, next) => {
>     // here we can manipulate the request before it is sent to Peerjs server
>     // If we don't authorize the user is just return a forbiden status code
>     return peerServer(req, res, next);
> });
> ```
> 
> my corrent problem is how to pass the token to the backend i tried ` path: '/myapp?access_token=SOMETHING'` but peerjs doens't seem to allow it, I will also try cookies and then let you guys known, but I havent found an args or something similar in the constructor of Peer({})

First of all, you gave me an insight to a solution of my problem, so thanks for sharing your experience. Secondly, You said that you tried to get the token _from peer_, how about trying to get it in the middleware '/peerjs' that you have? you can do that by getting the token either from the body (check out bodyParser) or from the query by using req.query.token, then authenticating before returning the peer server instance

**Comment by litch0** [comment]
Your are welcome, I'm happy to help. 
It worked, in the most part, I was getting the token, but I couldn't explore more with the time I've got, so If someone else has the same problem, they may come up with a different Idea, for now, I see no reason to leave this issue open.
