### ISSUE TITLE
Watchdog timer capability for PeerServer cloud service?

### ISSUE THREAD

**Issue by digable1** [peers/peerjs-server#277]
It looks like as I write this, the service is down.  This seems to happen periodically for a while - and then everything's good again.

The idea:  Add another item on the website peerjs.com - say "Cloud service status", with the last time a server ping/heartbeat check was run and the results, 'success' or 'it is down' (it could even notify an admin if it was down).

Thanks!

**Comment by jonasgloning** [comment]
Good idea, @digable1!

I created one [here](https://stats.uptimerobot.com/B7Ww3sDBVz).

I am not completely satisfied, it’s a bit slow and the domain is not customized. But it includes notifications for the admins and it's free.

It will be linked on the official site once the domain is transferred and the cloud service is up and running again.

Leaving this open as a reminder.

**Comment by digable1** [comment]
Thanks!

Look forward to completion and this helping to keep future down-time to a minimum, as well as knowledge on what the status really is.

**Comment by digable1** [comment]
Will people who use their own server be able to top into this monitor?  Say by the use of query strings or tokens if there's a registration process?

And oh yeah:  Any idea when the cloud service will be up and running again?

**Comment by jonasgloning** [comment]
> Will people who use their own server be able to top into this monitor?  Say by the use of query strings or tokens if there's a registration process?

If it's public, for general use and expected to stay online for the foreseeable future (so an alternative to 0.peerjs.com), I may add the server to the page manually. Otherwise, probably no. But there are many vendors for custom status pages.

> And oh yeah:  Any idea when the cloud service will be up and running again?

https://github.com/peers/peerjs/issues/937#issuecomment-1086918283

**Comment by jonasgloning** [comment]
Link to the status page is now live
