### ISSUE TITLE
Does peerjs server horizontally scale automatically when deployed to kubernetes?

### ISSUE THREAD

**Issue by jacoby149** [peers/peerjs-server#281]
If the number of replicas is more than 1, is there a system in place that will still allow the peers to find another even if two peers are connecting to two different replicas of the same container?

**Comment by jonasgloning** [comment]
Sadly, no. HA is on the to-do list, but it will take time.

In the meantime: The public instance is handling millions of connections a day with 3% cpu on a tiny server. Scale itself shouldn’t be an issue.
