### ISSUE TITLE
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by tahayk** [peers/peerjs-server#290]
I have been using PeerJS server for a couple of months, and sometimes I notice that the server crashes because of this error: 

> RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

Unfortunately I couldn't find a way to reproduce it, any idea how to handle it or fix it ? 

Thank you in advance.

**Comment by tahayk** [comment]
@jonasgloning thank you very much, looking forward for the next release.

**Comment by intellix** [comment]
I don't think is completed @tahayk - commits which updated some codestyling were created referencing this ticket and closed. There wasn't anything relating to this ticket yet... I'm also eagerly awaiting it :)

**Comment by tahayk** [comment]
Hey @jonasgloning, I couldn't reproduce the error with your code,
I'm running a docker container, everything is here: https://github.com/openreplay/openreplay/tree/main/peers
I'm using peerjs-server with expressjs

**Comment by tahayk** [comment]
Thank you very much @jonasgloning 
I have been using `v1.0.0-rc.4` for the past 3 days, so far no issues, 
except that I'm still getting this issue:

```
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
     at Receiver.getInfo (/work/node_modules/ws/lib/receiver.js:171:14)
     at Receiver.startLoop (/work/node_modules/ws/lib/receiver.js:131:22)
     at Receiver._write (/work/node_modules/ws/lib/receiver.js:78:10)
     at writeOrBuffer (node:internal/streams/writable:390:12)
     at _write (node:internal/streams/writable:331:10)
     at Receiver.Writable.write (node:internal/streams/writable:335:10)
     at Socket.socketOnData (/work/node_modules/ws/lib/websocket.js:1162:35)
     at Socket.emit (node:events:527:28)
     at addChunk (node:internal/streams/readable:324:12)
     at readableAddChunk (node:internal/streams/readable:297:9) {
   code: 'WS_ERR_UNEXPECTED_RSV_2_3',
   [Symbol(status-code)]: 1002
 }
```
but this time I'm able to catch it using the following code: (it wasn't possible before): 
```js
const app = express();
const server = app.listen(PORT, HOST, () => {
    console.log(`App listening on http://${HOST}:${PORT}`);
});

const peerServer = ExpressPeerServer(server, {
    debug: true,
    path: '/',
    proxied: true,
    allow_discovery: false
});

const peerError = (error) => {
    console.error('Error type:');
    console.error(error.type);
    console.error('Error message:');
    console.error(error);
}
peerServer.on('error', peerError);
```
