### ISSUE TITLE
Servers connection event does not occurr

### ISSUE THREAD

**Issue by philippwiddra** [peers/peerjs-server#32]
Hi peers team,
With the following node.js code I somehow do not get any `connection` events on the server but because the `disconnect` event occurrs somehow peers can connect.
Am I doing something wrong?

``` javascript
var PeerServer = require("peer").PeerServer;
var peerServer = new PeerServer({ port: 8081 });

peerServer.on("connection", function (id) {
    console.log("Peer connection event:", id);
});
peerServer.on("disconnect", function (id) {
    console.log("Peer disconnect event:", id);
});
```

**Comment by antonyadhiban** [comment]
Even after this fix I do not get the connection event happening. disconnect does happen though. I run the peerserver with express. @michelle
