### ISSUE TITLE
HTTPS SSL gotcha

### ISSUE THREAD

**Issue by redannick** [peers/peerjs-server#33]
Just wanted to point out to anyone else trying this, node will ignore self signed certificates. So if you're trying to run this over https you need a real certificate.

It may be that this can be adjusted in a setting somewhere, but I'm not sure where this would be in the dependency stack, so it was easier for me to just get a real certificate.

**Comment by luongnv89** [comment]
@sameer293 Did you manage this problem?

**Comment by sameer293** [comment]
@luongnv89 not yet.

**Comment by clarencechen** [comment]
@redannick @michelle @sameer293 @luongnv89 This problem is still happening in 2017 :(

**Comment by luongnv89** [comment]
@clarencechen I follow the tutorial in this: (https://www.npmjs.com/package/peer)[https://www.npmjs.com/package/peer], and it works for me.

This is how I did it:

```
var app = express()
var ExpressPeerServer = require('peer').ExpressPeerServer
var peerjs_options = {
    debug: true
}
var ssl_options ={
    key:fs.readFileSync('./certificate/myserver.key'),
    ca:fs.readFileSync('./certificate/GandiStandardSSLCA2.pem'),
    cert:fs.readFileSync('./certificate/certificate.crt'),
    honorCipherOrder: true,
    ciphers: 'ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:HIGH:!RC4:!MD5:!aNULL:!EDH'
}
var server = https.createServer(ssl_options,app)
var peerServer = ExpressPeerServer(server, peerjs_options)

... set your app router ... 

app.use('/myapp', peerServer)
server.listen(443)
```
Hope this help

**Comment by clarencechen** [comment]
Are there any files or strings I should obtain?
Thanks so much in advance

**Comment by sreekj** [comment]
@SameerRathod 
Sameer, were you able to get over this issue ?

**Comment by afrokick** [comment]
Use lets encrypt to obtain cert and key, then use it for reverse proxy or pass in options

```bash
node ./src/index.js --sslCertPath /path/to/cert.pem --sslKeyPath /path/to/key.key
```

**Comment by redannick** [comment]
@afrokick does this help with local https development?

**Comment by redannick** [comment]
I only mention it as I believe this was what I was doing in the first place. I was testing something that required https so expected a self cert to work. I suppose you could spoof a domain in your hosts file perhaps to use a let's encrypt certificate locally or put it on a temporary domain and this was my original workaround, but really, shouldn't a self cert work in the first place?

**Comment by AlexErrant** [comment]
> I suppose you could spoof a domain in your hosts file... shouldn't a self cert work in the first place?

I [do this](https://github.com/AlexErrant/Pentive/blob/main/peer/server.ts) in my project, and document how to "get started" [here](https://github.com/AlexErrant/Pentive/blob/main/design-decisions/run-locally.md). The steps aren't specific to PeerJS, but you should be able to understand how `mkcert` works and generate your own key/cert and update your hosts file for peerjs-server from that doc.
