### ISSUE TITLE
Can peerjs server be deployed on more than one process?

### ISSUE THREAD

**Issue by szimek** [peers/peerjs-server#34]
Can I run peerjs server on more than one process (e.g. dyno on Heroku, or drone on Nodejitsu)? E.g. Socket.io has different stores (by default it's memory store, but it can be switched e.g. to Redis) to allow running it on multiple processes.

Where peerjs server is currently hosted and what kind of traffic does it get? I'll have to deploy it on my own server (I need SSL) and unfortunately I have very little experience with managing servers, especially Node.js and WebSockets.

**Comment by pankydcoder** [comment]
@szimek / @michelle : I stumbled upon this and have a similar use case where I want to deploy peerjs on multiple instances at backend routed through an ALB. How did you achieve this?

**Comment by szimek** [comment]
@pankydcoder I switched from raw WebSockets to Firebase. I modified the PeerJS client library to use Firebase, and I'm not running PeerJS server at all. Here's the modified client library I'm using right now (it uses very outdated Firebase client): https://github.com/szimek/sharedrop/blob/master/vendor/peer.js.
