### ISSUE TITLE
Sometimes a peer leaving does not correctly free up its ID.

### ISSUE THREAD

**Issue by michelle** [peers/peerjs-server#4]
Check if WS is closing correctly. If not, there's not much that can be done.

**Comment by charms9** [comment]
We are experiencing connections that are not being released by the peer server. I am attempting to merge in the max_pings_missed option to the lib/server.js file referenced above, however I am not sure if that is going to work without additional changes. I am hoping that the max_pings_missed option could be added to the main peer server branch.

**Comment by laike9m** [comment]
Yes, I experienced this bug every day...

**Comment by stevedekorte** [comment]
+1

I'm seeing this as well.

**Comment by afrokick** [comment]
fixed in #139
