### ISSUE TITLE
Cross-origin issue

### ISSUE THREAD

**Issue by zkat** [peers/peerjs-server#49]
I tried running the current version of peerjs-server and got CORS errors because the CORS headers weren't present. I looked through the code and noticed the http app is supposed to be adding them, but I didn't see them when making requests manually, and the middleware util that adds the headers didn't seem to be firing at all.

**Comment by zovt** [comment]
@peveuve thanks man, seems that this was the issue <3 and thanks @michelle for working to fix it.

**Comment by fyyyyy** [comment]
Having this issue with build:0.3.13 and Firefox 35.0.1
I did not see this issue before upgrading from 0.3.9 to 0.3.13 yesterday. Happens on localhost with express server. I will look into certificates.

**Comment by TensorTom** [comment]
Same issue on both Chrome and Firefox `CORS header ‘Access-Control-Allow-Origin’ missing`

**Comment by merksam** [comment]
Guys, if I'm not mistaken you can run [express version](https://github.com/peers/peerjs-server#combining-with-existing-express-app) of peerjs-server and add [cors](https://www.npmjs.com/package/cors) package to allow cross-origin requests.

**Comment by nboulikas** [comment]
> Guys, if I'm not mistaken you can run [express version](https://github.com/peers/peerjs-server#combining-with-existing-express-app) of peerjs-server and add [cors](https://www.npmjs.com/package/cors) package to allow cross-origin requests.

How?
