### ISSUE TITLE
cloud server down?

### ISSUE THREAD

**Issue by MatthiasLohr** [peers/peerjs-server#5]
Hello,

since a couple of minutes the cloud server seems to doesn't work anymore. I get empty http responses.

Best regards
Matthias

**Comment by webmasterdragon** [comment]
PeerServer is down?
Yesterday I could get peer_id with my peer api key.
But now It requests error happened.
What's up on peerjs server now?
And could not open peerjs.com here.
Thanks.

**Comment by ericmuyser** [comment]
Think we're down again

**Comment by kidandcat** [comment]
We are working to revive the project, while we setup the servers and adapt the internals of the library, you can use the server by configuring it:

var peer = new Peer({host: 'cloud.peer-js.com'});

**Comment by rejnok93** [comment]
Cloud server down again today? Getting the same error, not able to obtaid peer id...

**Comment by kidandcat** [comment]
Got the problem: https://www.bleepingcomputer.com/news/technology/ovh-data-center-burns-down-knocking-major-sites-offline/
