### ISSUE TITLE
Only the first part of client ID is used

### ISSUE THREAD

**Issue by daGrevis** [peers/peerjs-server#61]
When there's a long key used as client ID like `f95743c4-8a9f-448e-afd9-e2e06afcf33f02153775104`, only the first part is used. I know that because when I listen to “open“ event, I get back the first part of client ID which is `f95743c4-8a9f-448e-afd9-e2e06afcf33f`.

The length limit should be removed or there should be a warning that only the first characters will be used as a client ID.

**Comment by fyyyyy** [comment]
this may be a problem with the validation regex
```js
  // Ensure alphanumeric ids
  validateId: function(id) {
    // Allow empty ids
    return !id || /^[A-Za-z0-9_-]+(?:[ _-][A-Za-z0-9]+)*$/.exec(id);
  },

  validateKey: function(key) {
    // Allow empty keys
    return !key || /^[A-Za-z0-9_-]+(?:[ _-][A-Za-z0-9]+)*$/.exec(key);
  },

**Comment by stevedekorte** [comment]
Did you ever resolve this problem? I also need support for longer ids and I don't (yet) see were in the code this limit is. It connect to the server but listAllPeers won't share the long names of the peers.

**Comment by afrokick** [comment]
Server side currently doesn't check id, you can use any string you want
