### ISSUE TITLE
Use Socket.io in lib/server.js instead of websockets and xhr

### ISSUE THREAD

**Issue by reuben453** [peers/peerjs-server#64]
How about using socket.io instead of websockets and XHR? Changes will be required to the peerjs client library as well. I've tried it out, it works. I've not tested much, just some basic testing to see that peers are connecting to the server and each other. What do you guys think?
https://github.com/reuben453/peerjs-server/tree/use_socket_io
https://github.com/reuben453/peerjs/tree/use_socket_io

**Comment by michelle** [comment]
What's the benefit of using SocketIO?

**Comment by reuben453** [comment]
One benefit would be that SocketIO takes care of falling back to long polling, etc in case websockets are not supported by the client. Another is that the code becomes a little simpler.
However, the client side peerjs library doubles in size to about 100KB. I'm not sure if the advantages outweigh the disadvantages....

**Comment by shichongrui** [comment]
I'm not sure that this would be beneficial considering that the browsers that are going to support WebRTC aren't going to have issues with web sockets.

**Comment by reuben453** [comment]
That should also mean that xhr is not required...

**Comment by celevra** [comment]
+1
for me it would better fit into an application with allready existing socket.io server

**Comment by celevra** [comment]
also after working a few day's with your server it seems like it is very unstable in conjunction with nginx as proxy and express, setting trust proxy and so on doesn't helped, got a lot of disconnects, no auto reconnect and so on... My socket.io is very stable (on the same server, same express, same nginx), so i now try to run it as separate server (standalone) but i want to run it on port 443 on a separate address ... now chance... so please provide the server part socket.io compatible, don't try reinventing the wheel

**Comment by dlinx** [comment]
+1

**Comment by pculka** [comment]
+1

**Comment by afrokick** [comment]
We'll remove xhr long pooling in next major version.

As said @shichongrui modern browser with WebRTC should support WebRTC.
