### ISSUE TITLE
PeerJS Server EMPTY_RESPONSE prompting periodically

### ISSUE THREAD

**Issue by ruomwald** [peers/peerjs-server#70]
Good afternoon everyone,
The team and I are facing an issue while using PeerJS for a little WebRTC project while trying to establish a connection to our server peer.
The issue prompted oftenly between two test with one OK and no changes between tests. This is what we read in our browser Network tab : 

```
Request URL:
    http://server-ip:9000/peerjs/HelloWorldServer16/v2b3bzn3cbzw7b9/id?i=0

Request Headers
    Provisional headers are shown
Origin:
    http://localhost:8080
Referer:
    http://localhost:8080/
User-Agent:
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) 
    AppleWebKit/537.36 (KHTML, like Gecko) 
    Chrome/41.0.2272.118 Safari/537.36
Query String
    i:0
```

In the Console : 

```
POST 
http://server-ip:9000/peerjs/HelloWorldServer16/v2b3bzn3cbzw7b9/id?i=0 
net::ERR_EMPTY_RESPONSE
```

It ended with : 

```
WebSocket connection to 'ws://server-ip:9000/peerjs?key=peerjs&id=HelloWorldServer16&token=v2b3bzn3cbzw7b9' 
failed: Connection closed before receiving a handshake response
```

I let you look further about this issue and decide if it concerns a patch or not.

Thank you and good bye :-)

**Comment by Gigibit** [comment]
Same issue, have you found a solution?

**Comment by afrokick** [comment]
Please leave a new comment if it'll occur again
