### ISSUE TITLE
somebody try to stress test the server?

### ISSUE THREAD

**Issue by boynet** [peers/peerjs-server#73]
how many users can it handle? does it use websocket to keep connection open to the server?

and whats the right way to add more functionality like rooms? or finding available to chat users? create a new server to handle this or to extend this server? thanks

**Comment by dlinx** [comment]
+1

**Comment by klickagent** [comment]
+1

**Comment by afrokick** [comment]
It's only for test/prototyping/learning purposes. For production you should use your own server.
