### ISSUE TITLE
Disconnected from server. Cannot set timeout.

### ISSUE THREAD

**Issue by joshuaquek** [peers/peerjs-server#78]
Is there a way to prevent a timeout from the peerjs server? Even after changing the timeout to 0 in lib/index.js and the timeout to 0 in bin/peerjs, my client would still experience a timeout with the peerjs server and a popup would show, saying "Lost connection to server". Is there a way to prevent this?

**Comment by madwed** [comment]
Did you ever find a solution to this @joshuaquek? I'm having a similar issue on an old project.

**Comment by afrokick** [comment]
Please, try last version of master branch in PeerJS - it should send ping message
