### ISSUE TITLE
Question about installing server

### ISSUE THREAD

**Issue by jarodium** [peers/peerjs-server#80]
Hello all

I have a ubuntu 14.04 headless vps.
I have installed peerjs with nvm and I'm using latest node 0.12.

I run it with peerjs --port 9000
The first thing that appears when I start it, I get this:

Started PeerServer on 0.0.0.0, port: 9000, path: / (v. 0.2.8)

This is odd. I should have gotten the machines IP address instead of 0.0.0.0.
But, I can connect to the server, using the videochat example, but I cannot stream the video to the other peer.

On the firefox console I get something like RTCIce is deprecated and pc ( peerjs.js line 602 ) is not defined.

Is this an issue with the vps? if so, what might be the problem?
Thanks in advance.

**Comment by afrokick** [comment]
https://github.com/peers/peerjs-server/pull/118
--host xxx.xxx.xxx.xxx
