### ISSUE TITLE
https? peer.js:861 Mixed Content:

### ISSUE THREAD

**Issue by transonly** [peers/peerjs-server#85]
This is what i get:

    peer.js:861 Mixed Content: The page at 'https://chat.mememe.nl/lib/template/livecamTO/rtc/index.php'    was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint    'http://0.peerjs.com:9000/wqu3yvg60x5vobt9/id?ts=14502077456690.7175990029594879'. This request    has been blocked; the content must be served over HTTPS.

I allready host the peer.js on my own https server. What can i do more?

**Comment by webtech4rindia** [comment]
Hello Trnas,

Did you able to figure out the issue? Appreciate your help on this?

**Comment by fawzib** [comment]
any update?

**Comment by webtech4rindia** [comment]
Yes, In my case few files was loaded as http:// and site was truned as "https".. Changing links from "http" to https worked.

**Comment by fawzib** [comment]
thank you. will double check my code

**Comment by transonly** [comment]
Yes if figured it out but i don't remember what my mistake was. I host it myself now and everything works.
