### ISSUE TITLE
Starts to systematically refuse connections from peer with a given ID

### ISSUE THREAD

**Issue by teo1978** [peers/peerjs-server#89]
(please feel free to rephrase the title of the issue, that's the best I could come up with)

I have a peer-to-peer application where peer A is the first to be set up and waits for peer B to connect to it by knowing its id. So, the code on A's side is like:

```
// 1
peer=new Peer('givenID', { 
        host: 'myhost.com',
        port: 9000,
        key: 'whatever'
});
```

If that fails, then I fall back to:

```
// 2
peer=new Peer({ 
        host: 'myhost.com',
        port: 9000,
        key: 'mykey'
});
```

The idea is: peer A (of any given pair) tries to reuse the same ID that he used the last time. If he's lucky and it's not been taken by some other guy in the meantime (who is using it right now), it will work,  otherwise he'll start using a new one assigned by the server.

The thing is, I am still developing the application and I am the only one using it so far, so there's no reason why case 1 should ever fail in the first place - except perhaps very sporadically, if I close and reopen the peer too quickly or something like that, but then after a while it should work again with the same ID.

Instead, code snippet 1 works for a few times, but then it starts to _systematically fail forever_.

That is, I try to create a Peer with a given ID, and the server systematically refuses. In the Developer Tools of the application trying to create the peer I see an HTTP request to 

> http://myhost.com:9000/mykey/givenID/somekindoflongtoken/id?i=0

and the response is:

```
00000000000000000000000000000000000 <many more zeroes>
{"type": "HTTP-ERROR"}
```

Something is wrong in the server's way of managing IDs. A connection from a peer trying to use a given ID may be refused under specific conditions, such as if the ID is currently in use or if it has been "recently", but there's no way a given ID should start to be refused forever.

It seems that there's some sort of ID "leakage".

**Comment by teo1978** [comment]
I wonder whether this is a duplicate of this three-year-old issue:
https://github.com/peers/peerjs-server/issues/4

**Comment by c4xp** [comment]
Hi,
I have the same problem. It's driving me nuts :(
I even made a repo which always replicates
https://github.com/c4xp/peerjs-peerjsserver-chatroom
for this issue (happens between Firefox 55.0.2 64bit and Chrome 60.0.3112.101 64bit)
Any help is more then welcomed :(

P.S.
https://github.com/c4xp/peerjs-peerjsserver-chatroom/blob/master/firefox.log
https://github.com/c4xp/peerjs-peerjsserver-chatroom/blob/master/chrome.log

**Comment by afrokick** [comment]
WE added ping message from client. I think we can check last N messages from client and if it missed - drop connection.

I'll create a PR and link with this issue.

**Comment by afrokick** [comment]
#139
