### ISSUE TITLE
Run cloud server not on port 9000

### ISSUE THREAD

**Issue by michelle** [peers/peerjs-server#9]
Because some places have firewalls that block on non-web ports.

**Comment by Bek81** [comment]
really useful!

**Comment by salfredogonzalez** [comment]
You dont really say how are you running the server, there are two different ways at the docs, one peerjs -port 8080 by example and the other is with nodejs, changing the lisnteningn port.

**Comment by dlinx** [comment]
+1

**Comment by afrokick** [comment]
@kidandcat FYI

And maybe we should run nginx proxy to solve https issue if it exists

**Comment by afrokick** [comment]
Ok, test server works on 443
