### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by coddypotter** [peers/peerjs-server#91]
When i execute "peerjs --port 9000 --key peerjs" on my ubuntu 14.04LTS(VM on Microsoft Azure) i am getting following error
/usr/bin/env: node: No such file or directory

Please help.

**Comment by leedh** [comment]
Check whether node installed your system. If installed, see http://stackoverflow.com/a/26320915/6404493

**Comment by coddypotter** [comment]
I had encountered this while deploying on azure. 
thank you @leedh.
