### ISSUE TITLE
How to setup audio conference of say 5 people using peerjs.

### ISSUE THREAD

**Issue by coddypotter** [peers/peerjs-server#93]
Hello,
I found peerjs as an open source and i wanted to implement a simple audio conference application. I had some trouble installing the peerjs server. But i have installed it now on my azure vm. Now im stuck up at coding the app. please help with a tutorial link or with the steps. I know decent javascript.

Thanks

**Comment by luongnv89** [comment]
You can start from here: http://peerjs.com/docs/#start

Try to do it for 1-1 then you will know how to setup for 5 people

Good luck

**Comment by afrokick** [comment]
This is client side issue. Please open a another one in PeerJS if you have a question.
