### ISSUE TITLE
PeerServer Cloud service down? 

### ISSUE THREAD

**Issue by jessevdp** [peers/peerjs-server#97]
The cloud server seems to be down. Sending a request using either the public key displayed in the docs of peerJS, or creating a custom free key, sends back this error.

I hope this can be fixed soon! 

![image](https://cloud.githubusercontent.com/assets/15139826/22326730/25c272ac-e3b4-11e6-89e0-86cdaf947481.png)

![image](https://cloud.githubusercontent.com/assets/15139826/22326675/f7608958-e3b3-11e6-9df3-2caef7871cfa.png)

**Comment by jessevdp** [comment]
Seems to be a similar (closed) issue -> https://github.com/peers/peerjs-server/issues/5

**Comment by afrokick** [comment]
it works
